name: Build_Multiplatform
on: [push]

jobs:
  build_linux_release:
    name: Build Linux release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        include:
          - os: ubuntu-20.04
            zip_name: ubuntu_tnc
            generator: Unix Makefiles

    steps:
      - name: Build codec2 Linux
        if: matrix.os == 'ubuntu-20.04'
        run: |
          git clone https://github.com/drowe67/codec2.git
          cd codec2
          git checkout master
          mkdir build
          cd build
          cmake ../
          make
          mv src/libcodec2.so src/libcodec2_${{ matrix.os }}.so

      - name: LIST ALL FILES
        shell: bash
        run: |
          ls -R

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact-linux
          path: codec2/build/src/libcodec2_${{ matrix.os }}.so