name: Build_Multiplatform
on: [push]

jobs:
  build_linux_release:
    name: Build ${{ matrix.os }} release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, macOS-latest]
        include:
          - os: ubuntu-20.04
            libcodec2_name: libcodec2.so
            libcodec2_os_name: libcodec2_${{ matrix.os }}.so
            generator: Unix Makefiles

          - os: ubuntu-latest
            libcodec2_name: libcodec2.so
            libcodec2_os_name: libcodec2_${{ matrix.os }}.so
            generator: Unix Makefiles

          - os: macOS-latest
            libcodec2_name: libcodec2.dylib
            libcodec2_os_name: libcodec2_${{ matrix.os }}.dylib
            generator: Unix Makefiles

    steps:
      - name: Build codec2 ${{ matrix.os }}
        run: |
          git clone https://github.com/drowe67/codec2.git
          cd codec2
          git checkout master
          mkdir build
          cd build
          cmake ../
          make
          mv src/${{ matrix.libcodec2_name }} src/${{ matrix.libcodec2_os_name }}

      - name: LIST ALL FILES
        shell: bash
        run: |
          ls -R

      - uses: actions/upload-artifact@v3
        with:
          name: libcodec2_${{ matrix.os }}
          path: codec2/build/src/libcodec2_${{ matrix.os }}.so