name: Build_Multiplatform
on: [push]

jobs:
  build_linux_release:
    name: Build ${{ matrix.os }} release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, macos-11, macos-12, windows-2016]
        include:
          - os: ubuntu-18.04
            libcodec2_name: libcodec2.so
            libcodec2_os_name: libcodec2_ubuntu-1804.so
            generator: Unix Makefiles
            shell: bash

          - os: ubuntu-20.04
            libcodec2_name: libcodec2.so
            libcodec2_os_name: libcodec2_ubuntu-2004.so
            generator: Unix Makefiles
            shell: bash

          - os: ubuntu-22.04
            libcodec2_name: libcodec2.so
            libcodec2_os_name: libcodec2_ubuntu-2204.so
            generator: Unix Makefiles
            shell: bash

          - os: macos-11
            libcodec2_name: libcodec2.dylib
            libcodec2_os_name: libcodec2_macos-11.dylib
            generator: Unix Makefiles
            shell: bash

          - os: macos-12
            libcodec2_name: libcodec2.dylib
            libcodec2_os_name: libcodec2_macos-12.dylib
            generator: Unix Makefiles
            shell: bash

          - os: windows-2016
            libcodec2_name: libcodec2.dll
            libcodec2_os_name: libcodec2_windows-2016.dll

    steps:
      - name: Build codec2 ${{ matrix.os }}
        if: ${{!startsWith(matrix.os, 'windows') }}
        run: |
          git clone https://github.com/drowe67/codec2.git
          cd codec2
          git checkout master
          mkdir build
          cd build
          cmake ../
          make
          mv src/${{ matrix.libcodec2_name }} src/${{ matrix.libcodec2_os_name }}

      - name: Build codec2 ${{ matrix.os }}
        if: matrix.os == 'windows-2016'
        run: |
          git clone https://github.com/drowe67/codec2.git
          cd codec2
          git checkout master
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" -D CMAKE_MAKE_PROGRAM=mingw32-make.exe ../
          make
          mv src/${{ matrix.libcodec2_name }} src/${{ matrix.libcodec2_os_name }}

      - uses: actions/upload-artifact@v3
        with:
          name: libcodec2_${{ matrix.os }}
          path: codec2/build/src/${{ matrix.libcodec2_os_name }}

      - name: LIST ALL FILES
        shell: bash
        run: |
          ls -R
